name: rs
description: >-
  A simple and fast CLI tool to generate Flutter project structure like 
  Clean Architecture, MVVM or your custom Rahul Architecture.
version: 1.0.0
repository: https://github.com/your-username/rs

environment:
  sdk: ^3.2.0

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  rs: rs
