name: rs
description: A CLI tool to generate Flutter project structure based on architecture.
version: 1.0.1
homepage: https://github.com/berarahul/rs-cli
repository: https://github.com/berarahul/rs-cli.git
issue_tracker: https://github.com/berarahul/rs-cli/issues
documentation: https://github.com/berarahul/rs-cli/blob/main/README.md

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1
  lints: ^5.1.1
  test: ^1.26.3

executables:
  rs: rs
