name: rs
description: A CLI tool to generate Flutter project structure based on architecture.
version: 1.0.0
homepage: https://github.com/berarahul/rs
repository: https://github.com/berarahul/rs
issue_tracker: https://github.com/berarahul/rs/issues
documentation: https://github.com/berarahul/rs#readme

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1
  test: ^1.26.3

executables:
  rs: rs
